default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV['DATABASE_NAME'] || "whoami_development" %>
  username: <%= ENV['DATABASE_USER'] || "whoami" %>
  password: <%= ENV['DATABASE_PASSWORD'] || "shhhhItsASecret" %>
  port: <%= ENV['DATABASE_PORT'] || "5432" %>
  host: <%= ENV['DATABASE_HOST'] || "127.0.0.1" %>
development:
  <<: *default
  port: 5434
test:
  <<: *default
  database: whoami_test
  port: 5434
production:
  <<: *default
  database: whoami_production
  username: whoami
  password: <%= ENV['WHOAMI_DATABASE_PASSWORD'] %>
